version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: task_management_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--max-connections=1000',
      '--wait_timeout=28800',
      '--interactive_timeout=28800'
    ]
    restart: unless-stopped

volumes:
  mariadb_data: